### ISSUE TITLE
Create a class for creating a pydbconfig.yml file

### ISSUE THREAD

**Issue by akemalyildirim1** [akemalyildirim1/py-db-migrate#4]
```
database:
  host: localhost
  port: 5432
  username: your_db_username
  password: your_db_password
  database_name: your_db_name

migration_directory: pydbmigrations
log_level: info
```

This service will create this file with the given parameters. Also, there should be a function to get the parameters of it.
